import signIn from '@/pages/signIn'
import signUp from '@/pages/signUp'
import template from '@/pages/template'
import album from '@/pages/album'
import albumView from '@/pages/albumView'
import image from '@/pages/image'
import layoutShow from '@/pages/layoutShow'
import recycleBin from '@/pages/recycleBin'
import personalCenter from '@/pages/personalCenter'
export {signIn,signUp,template,album,albumView,image,layoutShow,recycleBin,personalCenter,invoicePage}